/* Apple/Darwin (CoreBluetooth) port of picoruby-ble — central/observer v1.
 * Implements the include/ble.h port-side ABI by delegating to the PicoBLEDarwin
 * Swift backend (CBCentralManager). The 4 shared functions (BLE_push_event/
 * BLE_heartbeat/BLE_write_data/BLE_read_data) are defined in src/mruby/ble.c and
 * MUST NOT be redefined here; the synthesized packets reach BLE_push_event when
 * src/mruby/ble.c's pop_packet drains the Swift FIFO (pble_drain_one) each tick. */
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <time.h>

#include "../../include/ble.h"
#include "ble_common.h"

/* Generated by `swift build -emit-clang-header-path` (see mrbgem.rake). */
#include "PicoBLEDarwin-Swift.h"

/* Set in BLE_init; routes power control to the right Swift backend. */
static int current_role = BLE_ROLE_NONE;

/* Same period the other ports use: ports/rp2040/ble.c's HEARTBEAT_PERIOD_MS and
 * the esp32 port's HEARTBEAT_PERIOD_US. */
#define HEARTBEAT_PERIOD_MS 1000

/* mrblib/ble.rb's run loop calls `heartbeat_callback if pop_heartbeat` every
 * poll, and pop_heartbeat only reports true once a port has called
 * BLE_heartbeat(). rp2040 drives that from a btstack timer and the esp32 port
 * from an esp_timer; CoreBluetooth offers no equivalent, and the Swift backend
 * is barred from calling into mruby-adjacent code (see ports/darwin/README.md),
 * so the period is measured here and driven from the VM thread instead.
 *
 * Without it heartbeat_callback never runs, which on a peripheral means nothing
 * ever calls pop_write_value: PicoBLEPeripheral.swift's didReceiveWrite pushes
 * no event, so an inbound write reaches the mruby write-value table and then
 * sits there unread, and the table only grows.
 *
 * Called from src/mruby/ble.c's pop_packet, this port's only per-tick VM-thread
 * entry point. The first call starts the period rather than firing, matching a
 * timer that is armed and then expires. */
void
picoruby_ble_darwin_heartbeat_tick(void)
{
  static bool started = false;
  static uint64_t last_ms = 0;
  struct timespec ts;
  uint64_t now_ms;

  if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0) return;
  now_ms = (uint64_t)ts.tv_sec * 1000 + (uint64_t)(ts.tv_nsec / 1000000);
  if (!started) {
    started = true;
    last_ms = now_ms;
    return;
  }
  if (now_ms - last_ms < HEARTBEAT_PERIOD_MS) return;
  last_ms = now_ms;
  BLE_heartbeat();
}

int
BLE_init(const uint8_t *profile, int ble_role)
{
  current_role = ble_role;
  if (ble_role == BLE_ROLE_PERIPHERAL) {
    /* Parse the ATT-DB blob and build the CoreBluetooth GATT server. */
    pble_peripheral_init(profile);
  } else {
    pble_central_init((int32_t)ble_role);
  }
  return 0;
}

void
BLE_hci_power_control(uint8_t power_mode)
{
  bool on = (power_mode == 1);  /* HCI_POWER_ON */
  if (current_role == BLE_ROLE_PERIPHERAL) {
    if (on) pble_peripheral_power_on(); else pble_peripheral_power_off();
  } else {
    if (on) pble_power_on(); else pble_power_off();
  }
}

void
BLE_gap_local_bd_addr(uint8_t *local_addr)
{
  /* CoreBluetooth hides the local MAC; the decoder only logs this string. */
  memset(local_addr, 0, 6);
}

uint8_t
BLE_discover_primary_services(uint16_t conn_handle)
{
  pble_discover_services(conn_handle);
  return 0;
}

uint8_t
BLE_discover_characteristics_for_service(uint16_t conn_handle, uint16_t start_handle, uint16_t end_handle)
{
  pble_discover_characteristics(conn_handle, (uint8_t)start_handle, (uint8_t)end_handle);
  return 0;
}

uint8_t
BLE_read_value_of_characteristic_using_value_handle(uint16_t conn_handle, uint16_t value_handle)
{
  pble_read_value(conn_handle, (uint8_t)value_handle);
  return 0;
}

uint8_t
BLE_discover_characteristic_descriptors(uint16_t conn_handle, uint16_t value_handle, uint16_t end_handle)
{
  pble_discover_descriptors(conn_handle, (uint8_t)value_handle, (uint8_t)end_handle);
  return 0;
}

uint8_t
BLE_write_value_of_characteristic_without_response(uint16_t conn_handle, uint16_t value_handle, const uint8_t *data, uint16_t size)
{
  pble_write_value(conn_handle, (uint8_t)value_handle, data, size);
  return 0;
}

uint8_t
BLE_write_characteristic_descriptor_using_descriptor_handle(uint16_t conn_handle, uint16_t descriptor_handle, const uint8_t *data, uint16_t size)
{
  pble_write_descriptor(conn_handle, (uint8_t)descriptor_handle, data, size);
  return 0;
}
