/* Apple/Darwin (CoreBluetooth) port of picoruby-ble — central/observer v1.
 * Implements the include/ble.h port-side ABI by delegating to the PicoBLEDarwin
 * Swift backend (CBCentralManager). The 4 shared functions (BLE_push_event/
 * BLE_heartbeat/BLE_write_data/BLE_read_data) are defined in src/mruby/ble.c and
 * MUST NOT be redefined here; the synthesized packets reach BLE_push_event when
 * src/mruby/ble.c's pop_packet drains the Swift FIFO (pble_drain_one) each tick. */
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#include "../../include/ble.h"
#include "ble_common.h"

/* Generated by `swift build -emit-clang-header-path` (see mrbgem.rake). */
#include "PicoBLEDarwin-Swift.h"

int
BLE_init(const uint8_t *profile, int ble_role)
{
  (void)profile;
  pble_central_init((int32_t)ble_role);
  return 0;
}

void
BLE_hci_power_control(uint8_t power_mode)
{
  if (power_mode == 1) {        /* HCI_POWER_ON */
    pble_power_on();
  } else {                      /* OFF / SLEEP */
    pble_power_off();
  }
}

void
BLE_gap_local_bd_addr(uint8_t *local_addr)
{
  /* CoreBluetooth hides the local MAC; the decoder only logs this string. */
  memset(local_addr, 0, 6);
}

uint8_t
BLE_discover_primary_services(uint16_t conn_handle)
{
  pble_discover_services(conn_handle);
  return 0;
}

uint8_t
BLE_discover_characteristics_for_service(uint16_t conn_handle, uint16_t start_handle, uint16_t end_handle)
{
  pble_discover_characteristics(conn_handle, (uint8_t)start_handle, (uint8_t)end_handle);
  return 0;
}

uint8_t
BLE_read_value_of_characteristic_using_value_handle(uint16_t conn_handle, uint16_t value_handle)
{
  pble_read_value(conn_handle, (uint8_t)value_handle);
  return 0;
}

uint8_t
BLE_discover_characteristic_descriptors(uint16_t conn_handle, uint16_t value_handle, uint16_t end_handle)
{
  pble_discover_descriptors(conn_handle, (uint8_t)value_handle, (uint8_t)end_handle);
  return 0;
}

uint8_t
BLE_write_value_of_characteristic_without_response(uint16_t conn_handle, uint16_t value_handle, const uint8_t *data, uint16_t size)
{
  pble_write_value(conn_handle, (uint8_t)value_handle, data, size);
  return 0;
}

uint8_t
BLE_write_characteristic_descriptor_using_descriptor_handle(uint16_t conn_handle, uint16_t descriptor_handle, const uint8_t *data, uint16_t size)
{
  pble_write_descriptor(conn_handle, (uint8_t)descriptor_handle, data, size);
  return 0;
}
