/* Apple/Darwin (CoreBluetooth) port of picoruby-ble — central/observer v1.
 * Implements the include/ble.h port-side ABI by delegating to the PicoBLEDarwin
 * Swift backend (CBCentralManager). The 4 shared functions (BLE_push_event/
 * BLE_heartbeat/BLE_write_data/BLE_read_data) are defined in src/mruby/ble.c and
 * MUST NOT be redefined here; the synthesized packets reach BLE_push_event when
 * src/mruby/ble.c's mrb_event_popped drains the Swift FIFO (pble_drain_one) each tick. */
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <dispatch/dispatch.h>

#include "../../include/ble.h"
#include "ble_common.h"

/* Generated by `swift build -emit-clang-header-path` (see mrbgem.rake). */
#include "PicoBLEDarwin-Swift.h"

/* Set in BLE_init; routes power control to the right Swift backend. */
static int current_role = BLE_ROLE_NONE;

/* Same period the other ports use: ports/rp2040/ble.c's HEARTBEAT_PERIOD_MS and
 * the esp32 port's HEARTBEAT_PERIOD_US. */
#define HEARTBEAT_PERIOD_MS 1000

/* mrblib/ble.rb's run loop calls heartbeat_callback when @event_queue pops a
 * :heartbeat symbol, pushed only when a port calls BLE_heartbeat(). rp2040
 * drives that from a btstack timer and the esp32 port from an esp_timer, both
 * armed independently of the VM thread. CoreBluetooth itself has no such
 * timer, but GCD does: a dispatch source timer, armed once here, plays the
 * same role. */
static void
start_heartbeat_timer(void)
{
  static dispatch_source_t timer = NULL;
  if (timer != NULL) return;
  timer = dispatch_source_create(DISPATCH_SOURCE_TYPE_TIMER, 0, 0,
                                  dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0));
  dispatch_source_set_timer(timer, dispatch_time(DISPATCH_TIME_NOW, 0),
                             HEARTBEAT_PERIOD_MS * NSEC_PER_MSEC, 0);
  dispatch_source_set_event_handler(timer, ^{ BLE_heartbeat(); });
  dispatch_resume(timer);
}

int
BLE_init(const uint8_t *profile, int ble_role)
{
  current_role = ble_role;
  if (ble_role == BLE_ROLE_PERIPHERAL || ble_role == BLE_ROLE_BROADCASTER) {
    /* Both roles advertise, which on CoreBluetooth means CBPeripheralManager.
     * A broadcaster has no ATT database, so profile is NULL here. */
    pble_peripheral_init(profile);
  } else {
    pble_central_init((int32_t)ble_role);
  }
  start_heartbeat_timer();
  return 0;
}

void
BLE_hci_power_control(uint8_t power_mode)
{
  bool on = (power_mode == 1);  /* HCI_POWER_ON */
  if (current_role == BLE_ROLE_PERIPHERAL || current_role == BLE_ROLE_BROADCASTER) {
    if (on) pble_peripheral_power_on(); else pble_peripheral_power_off();
  } else {
    if (on) pble_power_on(); else pble_power_off();
  }
}

void
BLE_gap_local_bd_addr(uint8_t *local_addr)
{
  /* CoreBluetooth hides the local MAC; the decoder only logs this string. */
  memset(local_addr, 0, 6);
}

uint8_t
BLE_discover_primary_services(uint16_t conn_handle)
{
  pble_discover_services(conn_handle);
  return 0;
}

uint8_t
BLE_discover_characteristics_for_service(uint16_t conn_handle, uint16_t start_handle, uint16_t end_handle)
{
  pble_discover_characteristics(conn_handle, (uint8_t)start_handle, (uint8_t)end_handle);
  return 0;
}

uint8_t
BLE_read_value_of_characteristic_using_value_handle(uint16_t conn_handle, uint16_t value_handle)
{
  pble_read_value(conn_handle, (uint8_t)value_handle);
  return 0;
}

uint8_t
BLE_discover_characteristic_descriptors(uint16_t conn_handle, uint16_t value_handle, uint16_t end_handle)
{
  pble_discover_descriptors(conn_handle, (uint8_t)value_handle, (uint8_t)end_handle);
  return 0;
}

uint8_t
BLE_write_value_of_characteristic_without_response(uint16_t conn_handle, uint16_t value_handle, const uint8_t *data, uint16_t size)
{
  pble_write_value(conn_handle, (uint8_t)value_handle, data, size);
  return 0;
}

uint8_t
BLE_write_characteristic_descriptor_using_descriptor_handle(uint16_t conn_handle, uint16_t descriptor_handle, const uint8_t *data, uint16_t size)
{
  pble_write_descriptor(conn_handle, (uint8_t)descriptor_handle, data, size);
  return 0;
}
